version: "3"

services:
  rtsp2hls:
    build: .
    image: rtsp2hls
    container_name: rtsp2hls
    ports:
      - 8000:8000
      - 8080:8080
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8000/ping || exit 1
      interval: 5m
      timeout: 10s
      retries: 3
